language: r
cache: packages
os: linux

jobs:
  include:
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=verbose

r_binary_packages:
  - covr

r_github_packages:
  - ropensci/webmockr@middens

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

r_check_args: "--as-cran --no-manual --no-build-vignettes"

notifications:
  email:
    on_success: change
    on_failure: change
